# Generated by Django 4.2.5 on 2023-10-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_like',
            new_name='no_of_likes',
        ),
    ]
